# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-12 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='posts',
            field=models.ManyToManyField(related_name='posts', to='blog.Post', verbose_name='Posts'),
        ),
    ]
